// Builds demo/RUN.md from the JSON files written by scripts/demo.mjs.
//
//   npm run report                      latest contract
//   CONTRACT_ADDRESS=0x... npm run report

import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const RUNS_DIR = new URL("../demo/runs/", import.meta.url);
const OUTPUT = new URL("../demo/RUN.md", import.meta.url);

const runs = readdirSync(RUNS_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort()
  .map((f) => JSON.parse(readFileSync(new URL(f, RUNS_DIR), "utf8")));

if (runs.length === 0) {
  throw new Error("No runs found in demo/runs. Run `npm run demo` first.");
}

const contract = (process.env.CONTRACT_ADDRESS ?? runs.at(-1).contract).toLowerCase();
const selected = runs.filter((r) => r.contract?.toLowerCase() === contract);
const first = selected[0];
const explorer = first.explorer.replace(/\/address\/.*$/, "");

const tx = (hash) => `[\`${hash.slice(0, 10)}…${hash.slice(-8)}\`](${explorer}/tx/${hash})`;
const byHash = new Map(selected.flatMap((r) => r.transactions).map((t) => [t.hash, t]));
const deploy = selected.flatMap((r) => r.transactions).find((t) => t.label.startsWith("deploy"));

const lines = [
  "# AgentCourt on GenLayer Studio",
  "",
  "Generated by `npm run report` from the transaction receipts recorded by `npm run demo`.",
  "",
  "| | |",
  "|---|---|",
  `| Network | ${first.network} (chain ID \`${first.chainId}\`) |`,
  `| RPC | \`${first.rpc}\` |`,
  `| Contract | [\`${first.contract}\`](${first.explorer}) |`,
  deploy ? `| Deploy transaction | ${tx(deploy.hash)} |` : null,
  `| Buyer agent | \`${first.buyer}\` |`,
  `| Seller agent | \`${first.seller}\` |`,
  `| Run | ${first.startedAt} |`,
  "",
].filter((l) => l !== null);

for (const scenario of selected.flatMap((r) => r.scenarios)) {
  const a = scenario.agreement;
  const sellerAmount = Math.floor((a.amount * a.completion_percent) / 100);

  lines.push(
    `## Agreement #${scenario.agreementId}: ${scenario.title}`,
    "",
    "| Step | Sender | Transaction | Result | Validators agreed |",
    "|---|---|---|---|---|",
  );
  for (const hash of scenario.transactions) {
    const t = byHash.get(hash);
    const step = t.label.split(": ")[1];
    lines.push(
      `| \`${step}\` | ${t.role} | ${tx(hash)} | ${t.execution === "FINISHED_WITH_RETURN" ? "success" : t.execution} | ${t.votes.agree}/${t.votes.total} |`,
    );
  }

  lines.push(
    "",
    `**Verdict:** \`${a.verdict}\`, completion ${a.completion_percent}%, confidence ${a.confidence}%`,
    `(resolution \`${a.resolution}\`).`,
    "",
  );
  if (a.settled) {
    lines.push(
      `**Settlement accounting:** seller ${sellerAmount} / buyer refund ${a.amount - sellerAmount} of ${a.amount}.`,
      "",
    );
  }
  lines.push("<details><summary>Agreement terms, evidence and claims</summary>", "");
  lines.push("**Terms**", "", "> " + a.terms, "");
  lines.push("**Seller evidence**", "", "```text", a.evidence, "```", "");
  lines.push("**Seller claim**", "", "> " + a.seller_claim, "");
  if (a.buyer_claim) lines.push("**Buyer dispute**", "", "> " + a.buyer_claim, "");
  lines.push("</details>", "");

  if (a.resolution === "ADJUDICATED") {
    lines.push("**Evidence summary (stored on chain)**", "", "> " + a.evidence_summary, "");
    lines.push("**Reasoning (stored on chain)**", "", "> " + a.reasoning, "");
  }
}

writeFileSync(OUTPUT, lines.join("\n"));
console.log(`Wrote ${OUTPUT.pathname}`);
